services:
  postgres:
    image: postgres:16-alpine
    container_name: hisaab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hisaab
      POSTGRES_PASSWORD: hisaab123
      POSTGRES_DB: hisaab_erp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
